homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 45.4168
  longitude: -73.4992
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Toronto
  # Customization file
  customize: !include customize.yaml

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Show the introduction message on startup.
introduction:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Discover some devices automatically
discovery:
  enable:
    - homekit

# Sensors
sensor:
  # Weather prediction
  - platform: yr
 
  - platform: foobot
    token: !secret foobot_token
    username: !secret foobot_username

  - platform: awair_cust
    token: !secret awair_token
    name: Glow
    monitored_conditions:
      - temperature
      - humidity
      - co2
      - chemicals
    refresh_rate: 15
  - platform: awair_cust
    token: !secret awair_token
    name: Awair2
    monitored_conditions:
      - temperature
      - humidity
      - co2
      - chemicals
      - dust
    refresh_rate: 15
  - platform: awair_cust
    token: !secret awair_token
    name: Omni
    monitored_conditions:
      - temperature
      - humidity
      - co2
      - chemicals
      - dust
    refresh_rate: 15
  - platform: awair_cust
    token: !secret awair_token
    name: Awair1
    monitored_conditions:
      - temperature
      - humidity
      - co2
      - chemicals
      - dust
    refresh_rate: 15
  - platform: ring
    
    
# Text to speech
tts:
  - platform: google

dyson:
  username: !secret dyson_username
  password: !secret dyson_password
  language: CA
  devices:
    - device_id: PT3-CA-JMA3143A #Dyson Hot Cool Office
      device_ip: 10.101.0.129
    - device_id: NA7-US-HMA0563A  #Dyson Fan Master Bedroom
      device_ip: 10.101.0.121

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret
  
aerogarden:
    username: !secret aerogarden_username
    password: !secret aerogarden_password

abode:
  username: !secret abode_username
  password: !secret abode_password
  name: Abode Alarm System
  polling: False


ring:
  username: !secret ring_username
  password: !secret ring_password

binary_sensor:
  - platform: ring

camera:
  - platform: ring  

light:
  - platform: osramlightify
    host: 10.101.0.176

point:
  client_id: !secret minut_clientid
  client_secret: !secret minut_clientsecret


alexa_media:
  accounts:
    - email: !secret amazon_username
      password: !secret amazon_password
      url: amazon.ca  
      
notify:
  - platform: alexa_media
    name: alexa_media

    
homekit:
  autostart: false
  filter:
    include_domains:
      - light
      - binary_sensor
      - sensor
      - climate
      - fan
    include_entities:
      - light.eve_light_strip_8606
    exclude_entities:
      - binary_sensor.keyfob
      - binary_sensor.qa_notification
      - binary_sensor.remote_ui
      - binary_sensor.ring_front_doorbell_ding
      - light.nanoleaf_left
      - light.nanoleaf_right
      - script.alexa_announce_example
      - script.test_tts
      - sensor.basement_nest_protect_battery_health
      - sensor.basement_nest_protect_color_status
      - binary_sensor.qa_notification
      - binary_sensor.home_away
      - binary_sensor.hallway_point_tamper
      - binary_sensor.hallway_point_heat
      - binary_sensor.hallway_point_dry
      - binary_sensor.hallway_point_connectivity
      - binary_sensor.hallway_point_cold
      - binary_sensor.hallway_point_battery

panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: http://hassio.local:3218
    
 

recorder:
  purge_keep_days: 5
  exclude:
    domains:
      - automation
      - weblink
      - updater
    entities:
      - sun.sun # Don't record sun data
      - sensor.last_boot # Comes from 'systemmonitor' sensor platform
      - sensor.date
      
group: !include groups.yaml
automation: !include automations.yaml
script: !include_dir_merge_named script
